//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEDRATICO
    {
        public string ID_Catedratico { get; set; }
        public string Nombre_Catedratico { get; set; }
        public string Apellido_Catedratico { get; set; }
        public string Telefono_Catedratico { get; set; }
        public string Estado_Catedratico { get; set; }
    }
}
